[17기 조혜윤]ProductListView, SizeFilterView 작성
wecode-bootcamp-korea/17-2nd-shockX-backend pull request #5
Opened 2021-03-05 09:48 UTC by hyeyoonc

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 버튼 활성화 기능 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- id '@' 포함, pw 5 글자 이상 입력 시 버튼 활성화(예시)

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 함수 로직이 너무 긴 것 같습니다. 좀 더 효율적인 방법이 없을지 궁금합니다.(예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-03-05 10:09 UTC, soheon-lee commented
@hyeyoonc `csv_data` 모두 제거해주세요 :) 데이터가 공유되면 보안상 위헙하고, api 기능과는 별도인 파일이기 때문에 같은 레포지토리에서 관리 하지 않습니다

2021-03-05 10:09 UTC, soheon-lee commented
유닛테스트 없으면 리뷰 진행되지 않습니다 :) !

2021-03-08 00:43 UTC, soheon-lee commented
@hyeyoonc `data` 디렉토리랑 `db_uploader.py`아직 제거가 안됐습니다 혜윤님 
두 파일 제거를 가장 우선적으로 해서 다시 push 부탁드립니다 💜

2021-03-08 01:05 UTC, soheon-lee commented
@hyeyoonc 혜윤님 이 PR 근데 model 먼저 빠르게 머지 되어야 하는 것 아닌가요? view 리뷰 다 받으실 때 까지 model merge 안되어도 괜찮은가요?

2021-03-08 07:37 UTC, hyeyoonc commented
data 디렉토리랑 db_uploader.py 삭제하고 push 했습니다^_^ 
그리고 model merge는 이전에 된거아닌가요? ㅎㅎ

2021-03-08 07:38 UTC, hyeyoonc commented
ProductDetailView 어마어마한 results['sizes']부분 리팩토링 도와주세요,,,제발요,,,plz,,,,,

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +        offset        = int(request.GET.get('offset', 0))
명확한 변수 이름과 잘 나눠진 pagination good good good!

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +            'productImage' : product.image_set.all()[0].image_url,
```suggestion
            'productImage' : product.image_set.first().image_url,
```
모든 객체 가운데 첫번째 요소만 선택하길 원하신다면 `first()` 메소드를 추천드립니다 :)

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +                        order_status__name       = ORDER_STATUS_CHECK)])}
해당 사이즈의 상품 (id) 가운데 order_status가 현재 진행중인 Ask들을 모두 가져와서 그 가운데 가장 낮은 가격을 고르시는 과정이 맞나요?

생각하시느라 정말 고생하셨겠어요 👍 👍 👍 👍 👍 
현재는 Database로 부터 모든 데이터를 전부 가져와서 파이썬 리스트 내부에서 min값을 찾고 있습니다.
이번에는 Database에서 데이터를 가져올 때부터 최소값만 가져올 수 있도록 코드를 리팩토링 하셨으면 합니다. Django에서 특정 조건으로, 특정 필드의 최소값을 가지는 데이터를 찾으실 수 있을 거에요 ! 화이팅 !
추천검색어는...`Django how to get minimum value in a certain column with condition` 와 비슷한 쪽으로? 드려봅니다

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +
`sizes`라는 변수를 15번째 라인에서 선언을 하셨는데, 이를 37번째 줄에서 사용하시고 있습니담
변수가 선언된 곳과 변수를 처음 사용하는 곳이 다소 떨어져있어서, `sizes`변수를 다시 거꾸로 찾아가야하는 과정이 생기게 되는데, 보통 자주 일어나는 일이지만, 가독성을 떨어트리는 요소가 됩니다 

이 클래스에서는 이 변수가 여기서 밖에 사용되고 있지 않기 때문에, 따로 변수로 선언하시기보다는 `Size.objects.all()` 를 37번째 줄에서 바로 사용하시는 것을 추천드립니다! :)

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +        return JsonResponse({'products': total_products, 'size_categories': size_categories}, status=200)
lowest_price와 hight_price가 동시에 있을 때와,
둘 가운데 하나만 있을 때.
이런 것도 가능하군요.. 

지금 보면 
41~46 번 줄까지의 코드가 완전히 동일하게 세 번 반복되고 있습니다. 
40번 줄도 사실은 filter()내부에 들어가는 조건만 달라지고 아래에서도 계속 활용되네요 :)
이럴 때에는 이 세 번 반복되는 동일한 코드의 구조를 한 번만 사용하는 방향으로 줄이셔야 합니다.

특히나 `elif`가 사용되는 경우가 거의 없도록 하는 것이 가독성 측면에서 파이썬 정규 규칙에서 지향하고 있는 바입니다 :)
자 혜윤님... 길고 긴 과정이 되겠지만 이 코드 8줄로 확 줄여보시죠!

2021-03-08 08:34 UTC, soheon-lee commented on product/views.py
> +        return JsonResponse({'products': total_products, 'size_categories': size_categories}, status=200)
엔드포인트를 분리하는 기준은 해당 엔드포인트가 다루는 데이터입니다. 서로 다른 resource를 다루는 엔드포인트라면 분리되어야 하지만, Filter 뷰도 결국 Product 데이터에 접근하는 엔드포인트입니다. 따라서 RESTful API 관점에서 ProductList뷰와 같은 엔드포인트라고 할 수 있습니다. 필터 키워드는 query string 을 이용하여 통신해보세요 🙂

2021-03-08 08:37 UTC, soheon-lee commented
@hyeyoonc 
한 PR에 Detail과 List가 둘 다 있는 것은 진행 속도를 매우 늦어지게 만듭니다.
두 코드 서로 PR 분리해서 올려주세요. 그리고 test code 없는 상태에서 `리뷰 요청` 라벨은 의미가 없습니다 ㅠㅠ
우선 핵심적인 것들 먼저 리뷰드립니다.

1. ListView, DetailView PR 분리
2. 테스트코드 작성

우선순위는 위와 같습니다. PR을 잘 정리해나가는 것도 개발할 때 꼭 해야하는 일입니담 정리해주세요~

2021-03-09 01:41 UTC, hyeyoonc commented on product/views.py
> +            'productImage' : product.image_set.all()[0].image_url,
네 변경했습니다~

2021-03-09 15:13 UTC, hyeyoonc commented on product/views.py
> +                        order_status__name       = ORDER_STATUS_CHECK)])}
오 감사합니당~~~ 변경했습니다🌱

2021-03-09 15:15 UTC, hyeyoonc commented on product/views.py
> +
앗 네네!!

2021-03-09 15:20 UTC, hyeyoonc commented on product/views.py
> +        return JsonResponse({'products': total_products, 'size_categories': size_categories}, status=200)
넵😊

2021-03-09 23:38 UTC, ulfrid requested changes
확인 바랍니다~

2021-03-09 23:38 UTC, devops-andrew commented on product/tests.py
> +        client = Client()
매번 클라이언트를 선언하기보단 클래스 상단에 한번 선언해두고 호출하는게 더 좋을것 같습니다~!

2021-03-10 00:47 UTC, hyeyoonc commented on product/tests.py
> +        client = Client()
네넵ㅎㅎ수정했습니다~~

2021-03-10 01:54 UTC, ulfrid commented
LGTM👍

2021-03-10 01:54 UTC, merged